organization: "vishutyagi0210"

# Global defaults for all repositories
defaults:
  history_depth: 5
  fetch_cache: true
  fetch_contributors: true
  fetch_issues_prs: true

# List repositories specifically. If "repositories" is empty or omitted, it fetches ALL repos in the org using the defaults.
# If you list repositories here, it will ONLY fetch these repositories.
repositories:
  - name: "Dashboard"
    history_depth: 10
  - name: "POC_PR_ALERT"
  - name: "kubeadm-k8s-setup"
  - name: "github-ci-cd-with-labs"
